version: '3'

services: 
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks: 
      - node-network
    depends_on: 
       - node

  node:
    build: 
      context: node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s /usr/local/bin/docker-entrypoint.sh
    command: ['node', 'index.js']
    networks: 
      - node-network
    volumes: 
      - ./node/index.js:/www/index.js
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    # volumes: 
    #   - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
    

networks: 
  node-network:
    driver: bridge      
